name: Trigger Jenkins Build

on:
  push:
  branches: [main]

jobs:
  trigger-jenkins:
  runs-on: ubuntu-latest
  steps:
    - name: Trigger Jenkins Job
    env:
      JENKINS_URL: ${{ secrets.JENKINS_URL }}
      JENKINS_USER: ${{ secrets.JENKINS_USER }}
      JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
      JOB_NAME: "deploy-to-ubuntu-jenkindemo"
      BUILD_TOKEN: ${{ secrets.JENKINS_BUILD_TOKEN }}
    run: |
      curl -X POST \
      "$JENKINS_URL/job/$JOB_NAME/build?token=$BUILD_TOKEN" \
      --user "$JENKINS_USER:$JENKINS_API_TOKEN"